name: Build/Release HAWAI Projects

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Check Out Folder
        run: ls -R out

      - name: Build & Publish Electron App
        run: npm run build -- --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
